### ISSUE TITLE
Hacer mockup para un Post

### ISSUE THREAD

**Issue by BayronValenzuela** [BayronValenzuela/BlogueoLibre#2]
Debe contener al menos:
- Elementos en un Post
- Organización de un Post

**Comment by Blopv** [comment]
_Post necesita:_
- **Título**
- **Contenido** (_Archivos, texto, etc_)
- **Perfil de Autor** (Algunos datos como _foto de perfil, mail (o contacto), cantidad de posts, reseñas, entre otros._)
- **Ubicación**
- **Fecha**

_Botones:_
Vistos por autor:
- **Modo público/privado**
- **Editar**

Vistos por todos:
- **Like (Con contador)**
- **Comentarios (Con contador, mostrando vista previa de algunos)**
- **Ver más (Redirige a casilla de comentarios)**

![Mockup Básico Post 1 0](https://user-images.githubusercontent.com/72423259/98706101-33a03480-235d-11eb-9eae-3994f08b2944.png)
